name: HacktoberFest 2021
title: "[HacktoberFest- 2021]: "
labels: ["hacktoberfest2021"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Feedback
      description: Tell us about your experience!
  - type: textarea
    id: next_workshop
    attributes:
      label: What technology would you like to learn next??
      description: What workshop should we conduct next?